Support numbers as file flag values
browser-fs/core pull request #29
Opened 2023-12-23 23:21 UTC by kkoreilly

This PR adds support for specifying `FileFlag` values as numbers. This behavior is consistent with Node.js (see https://nodejs.org/api/fs.html#file-system-flags). It also makes the constants added as a result of https://github.com/jvilk/BrowserFS/issues/216 useful.

2023-12-25 01:30 UTC, dr-vortex reviewed
Thank you very much for this PR! There are a couple of small things but overall it looks solid.

2023-12-25 01:30 UTC, dr-vortex commented on src/file.ts
> +	public static stringFromNumber(flag: number): string {
Static methods should follow `PascalCase`.

2023-12-25 01:30 UTC, dr-vortex commented on src/file.ts
> +		switch (flag) {
Please do `npm run format`. You will also want to do `npm run lint`.

2023-12-25 05:58 UTC, kkoreilly commented
I updated the formatting and converted the name to `PascalCase`.

2023-12-27 02:38 UTC, dr-vortex requested changes
If you haven't done so already, make sure to run `npm run format`

2023-12-27 02:38 UTC, dr-vortex commented on src/file.ts
> +		}
Please use guard clauses in the constructor:
```ts

if(typeof flag == 'number') {
    flag = FileFlag.StringFromNumber(flag);
}

if (FileFlag.validFlagStrs.indexOf(flag)) { 
                                 throw new ApiError(ErrorCode.EINVAL, 'Invalid flag string: ' + flag); 

this.flagStr = flag;
```

2023-12-27 05:52 UTC, kkoreilly commented
I updated it to use to guard clauses and ran `npm run format` again.

2023-12-27 11:45 UTC, dr-vortex approved these changes
Great, thank you!

2023-12-27 11:45 UTC, merged